connection: &connection
  adapter: postgresql
  encoding: unicode
  host:     localhost
  pool: 5
  username: workshops
  password: test12345

development:
  <<: *connection
  database: workshops_development
  username: workshops
  password: test12345

test: &test
  <<: *connection
  database: workshops_test
  username: workshops
  password: test12345
